apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
        - name: cliente
          image: diogoerie/cliente:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081
