version: '3.9'

services:
  eurekaserver:
    build:
      context: ./eurekaserver
    ports:
      - "8761:8761"

  cliente:
    build:
      context: ./cliente
    ports:
      - "8081:8081"
    depends_on:
      - eurekaserver

  veiculos:
    build:
      context: ./veiculos
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver
