apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: veiculos
  template:
    metadata:
      labels:
        app: veiculos
    spec:
      containers:
        - name: veiculos
          image: diogoerie/veiculos:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8082
